### 普通版本技术交底书模型
upstream disclosure_service_v1 {
        server 192.168.88.250:8890;
        server 192.168.88.250:8894;
    }


### 权利要求书模型
upstream claims_service_v1 {
      server 192.168.88.250:8892;
      server 192.168.88.250:8896;
  }

### 权利要求书模型
upstream claims_v2 {
      server 192.168.88.250:8897;
  }

### 说明书模型
upstream figures_service_v1 {
      server 192.168.88.250:8893;
      server 192.168.88.250:8895;
  }

### 权要-ptn-32b-测试模型
upstream claims_ptn_32b_service_v1 {
      server 192.168.88.250:8894;
  }


server {
    listen 80;
    server_name _;
    root /data/build;

    # location /model/service/v1/ {
    #   proxy_pass http://localhost:8890/v1;
    #   include proxy.conf;
    # }

    # /PatXGPT模型开放的是 http://:8890/model/service/v1/
    # 让外部请求的api路径是/model/service/v1       其实转发到了/v1
    location /model/service/v1 {
      rewrite ^/model/service/v1(/.*)$ /v1$1 break;
      # proxy_pass http://192.168.88.250:8890;
      proxy_pass http://disclosure_service_v1;
      include proxy.conf;
    }


    # /PatXGPT_RJ模型开放的是http://:8891/model/service/v1/
    # 准备让外部请求/model/renjie/service/v1
    location /model/renjie/service/v1 {
      rewrite ^/model/renjie/service/v1(/.*)$ /v1$1 break;
      proxy_pass http://192.168.88.250:8891;
      include proxy.conf;
    }

    # /LLaMA-Factory模型, 权利要求书内容生成，开放的是http://:8892/model/service/claims/v1
    # 准备让外部请求/model/service/claims/v1
    location /model/claims/service/v1 {
      rewrite ^/model/claims/service/v1(/.*)$ /v1$1 break;
      # proxy_pass http://192.168.88.250:8892;
      proxy_pass http://claims_service_v1;
      include proxy.conf;
    }

    # /LLaMA-Factory模型, 权利要求书内容生成v2，开放的是http://:8897/model/service/claims2/v1
    # 准备让外部请求/model/service/claims/v2
    location /model/claims2/service/v1 {
      rewrite ^/model/claims2/service/v1(/.*)$ /v1$1 break;
      proxy_pass http://claims_v2;
      include proxy.conf;
    }


    # /LLaMA-Factory模型, 说明书内容生成，开放的是http://:8893/model/instruction/service/v1
    # 准备让外部请求/model/instruction/service/v1
    location /model/instruction/service/v1 {
      rewrite ^/model/instruction/service/v1(/.*)$ /v1$1 break;
      # proxy_pass http://192.168.88.250:8893;
      proxy_pass http://figures_service_v1;
      include proxy.conf;
    }

    # 权要-ptn-32b-测试模型开放的是 http://:8894/model/claims/ptn/32b/service/v1
    # 让外部请求的api路径是/model/claims/ptn/32b/service/v1     其实转发到了/v1
    location /model/claims/ptn/32b/service/v1 {
      rewrite ^/model/claims/ptn/32b/service/v1(/.*)$ /v1$1 break;
      # proxy_pass http://192.168.88.250:8890;
      proxy_pass http://claims_ptn_32b_service_v1;
      include proxy.conf;
    }

    location /xinference{
      rewrite ^/xinference(/.*)$  $1 break;
      proxy_pass http://192.168.88.250:8898;
      include proxy.conf;
    }


    location @router {
      rewrite ^.*$ /index.html last;
    }
}