server {
    listen 80;
    server_name _;
    root /data/build;

    # location /model/service/v1/ {
    #   proxy_pass http://localhost:8890/v1;
    #   include proxy.conf;
    # }

    # /PatXGPT模型开放的是 http://:8890/model/service/v1/
    # 让外部请求的api路径是/model/service/v1       其实转发到了/v1
    location /model/service/v1 {
      rewrite ^/model/service/v1(/.*)$ /v1$1 break;
      proxy_pass http://192.168.88.250:8890;
      include proxy.conf;
    }


# 118.178.241.227 - - [12/Aug/2024:03:22:49 +0000] "POST /model/renjie/service/v1/chat/completions HTTP/1.1" 200 2283 "-" "python-requests/2.31.0" "-"
# 118.178.241.227 - - [12/Aug/2024:03:23:11 +0000] "POST /model/claims/service/v1/chat/completions HTTP/1.1" 404 112 "-" "python-requests/2.31.0" "-"
    # /PatXGPT_RJ模型开放的是http://:8891/model/service/v1/
    # 准备让外部请求/model/renjie/service/v1
    location /model/renjie/service/v1 {
      rewrite ^/model/renjie/service/v1(/.*)$ /v1$1 break;
      proxy_pass http://192.168.88.250:8891;
      include proxy.conf;
    }

    # /LLaMA-Factory模型, 权利要求书内容生成，开放的是http://:8892/model/service/claims/v1
    # 准备让外部请求/model/service/claims/v1
    location /model/claims/service/v1 {
      rewrite ^/model/claims/service/v1(/.*)$ /v1$1 break;
      proxy_pass http://192.168.88.250:8892;
      include proxy.conf;
    }


    # /LLaMA-Factory模型, 说明书内容生成，开放的是http://:8893/model/service/claims/v1
    # 准备让外部请求/model/instruction/service/v1
    location /model/instruction/service/v1 {
      rewrite ^/model/instruction/service/v1(/.*)$ /v1$1 break;
      proxy_pass http://192.168.88.250:8893;
      include proxy.conf;
    }



    location /xinference{
      rewrite ^/xinference(/.*)$  $1 break;
      proxy_pass http://192.168.88.250:8898;
      include proxy.conf;
    }


    location @router {
      rewrite ^.*$ /index.html last;
    }
}